#!/usr/bin/env sh
################################################################################
# Gradle start up script for UN*X
#
# Generated by the Gradle wrapper
################################################################################

set -e

APP_NAME="gradlew"
APP_BASE_NAME=$(basename "$0")
DIRNAME=$(dirname "$0")

if [ -z "$DIRNAME" ]; then
  DIRNAME="."
fi

APP_HOME="$DIRNAME"

# Resolve any symlinks
while [ -h "$0" ]; do
  ls=$(ls -ld "$0")
  link=$(expr "$ls" : '.*-> \(.*\)$')
  if expr "$link" : '/.*' > /dev/null; then
    target="$link"
  else
    target="$APP_HOME/$link"
  fi
  cd "$(dirname "$target")"
  target=$(basename "$target")
  APP_HOME=$(pwd -P)
  cd - >/dev/null
  set -- "$target"
done

cd "$APP_HOME" >/dev/null
APP_HOME=$(pwd -P)
cd - >/dev/null

DEFAULT_JVM_OPTS="-Xmx64m -Xms64m"

# Locate java
if [ -n "$JAVA_HOME" ] && [ -x "$JAVA_HOME/bin/java" ]; then
  JAVACMD="$JAVA_HOME/bin/java"
else
  JAVACMD="java"
fi

exec "$JAVACMD" $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS \
  -classpath "$APP_HOME/gradle/wrapper/gradle-wrapper.jar" \
  org.gradle.wrapper.GradleWrapperMain "$@"
